# AI服务后端
ai_backend:
  - # 推理服务
    type: llm
    name: ollama
    default_model: gpt-4o
    api_style: openai
    api_base: http://127.0.0.1:1234/v1/
    api_token: 123456
    http_proxy: http://xxxx
    http_timeout: 10s
  - # TTS服务
    type: tts
    name: ollama
    default_model: tts-1
    api_style: openai
    api_base: http://127.0.0.1:1234/v1/
    api_token: 123456
    http_timeout: 10s
  - # STT服务
    type: stt
    name: ollama
    default_model: whisper-1
    api_style: openai
    api_base: https://api.openai.com/v1/
    api_token: sk-xxx
    http_timeout: 10s
  - # 图像服务
    type: image
    name: ollama
    default_model: dall-e-3
    api_style: openai
    api_base: http://127.0.0.1:1234/v1/
    api_token: 123456
    http_timeout: 10s
