# AI服务后端
ai_backend:
  # 推理服务
  llm:
    name: ollama
    # 风格
    type: openai
    api_base: http://127.0.0.1:1234/v1/
    api_token: 123456

  # TTS服务
  tts:
    name: ollama
    type: openai
    api_base: http://127.0.0.1:1234/v1/
    api_token: 123456

  # STT服务
  stt:
    name: ollama
    type: openai
    api_base: http://127.0.0.1:1234/v1/
    api_token: 123456

  # 图像服务
  image:
    name: ollama
    type: openai
    api_base: http://127.0.0.1:1234/v1/
    api_token: 123456
